# Generated by Django 4.2.16 on 2024-11-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Linkapp', '0004_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='post_image'),
        ),
    ]
