# .github/workflows/test.yml
name: Run Tests on Push

on:
  push:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install setuptools 
      run: |
        python -m ensurepip --upgrade
        pip install --upgrade setuptools

    - name: Install dependencies
      run: |
        cd Backend  
        cd djangoProject3
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd Backend  
        cd djangoProject3
        python manage.py runserver
