
name: Django CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: Linkapp
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        cd Backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h postgres -U postgres; do
          echo "Waiting for PostgreSQL...";
          sleep 3;
        done

    - name: Migrate database
      env:
        DB_NAME=Linkapp
        DB_USER=postgres
        DB_PASSWORD=123
        DB_HOST=postgres
        DB_PORT=5432 
      run: |
        cd Backend
        python manage.py migrate

    - name: Run check
      env:
        DB_NAME=Linkapp
        DB_USER=postgres
        DB_PASSWORD=123
        DB_HOST=postgres
        DB_PORT=5432 
      run: |
        cd Backend
        python manage.py check
